FROM python:3.11-slim

WORKDIR /app

COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt

COPY config.yaml .
COPY src ./src

ENV PYTHONPATH=/app
ENV CONFIG_PATH=/app/config.yaml

CMD ["python", "-m", "src.train"]
